---
- hosts: grup1
  user: centos
  become: yes
  vars:
    hostname: toomistm
    domain_name: sa.cs.ut.ee
    ipv41: 172
    ipv42: 17
    ipv43: 88
    ipv44: 203
# VM ip is 172.17.88.203

  roles:
#    - { role: etais, tags: etais }
#    - { role: dns, tags: dns }
#    - { role: apache, tags: apache }
    - {role: email, tags: email }
